mode: simulation

simulation:
  name: fc.A4.9WT
  is_dynamic: True
  total_time: 800. # s
  time_step: 1. # s
  dimensions: 2 # -
  save_logs: True
  write_time_step: 10.0

flow:
  type: "steady"
  inflow_velocity: [7.7, 225.]  # [|U|, theta]
  kinematic_viscosity: 0.000015 # kg.m^-1.s^-1
  tuning_viscosity: 1. # kg.m^-1.s^-1
  mixing_length: 10. #30. #20 # m
  wake_mixing_length: 1.5 # D
  wake_mixing_width: 0.6  # D
  wake_mixing_offset: 3.0 # D
  wake_mixing_ml_max: 25 # m
  density: 1.2 # kg.m^-3
  continuity_correction: wfsim_gen # none, wfsim, (general)
  finite_element: MINI # TH, MINI

wind_farm:
  size: [5000,5000]
  cells: [25, 25]
  do_refine_turbines: 3 # n refinements
  refine_radius: 200. # m
  positions: # [x, y] m
    - [2143.3,  378.2]
    - [3025.9, 1260.8]
    - [3908.4, 2143.3]
    - [1260.8, 1260.8]
    - [2143.3, 2143.3]
    - [3025.9, 3029.9]
    - [ 378.2, 2143.3]
    - [1260.8, 3025.9]
    - [2143.3, 3908.4]
  yaw_angles: # [gamma] deg
    - 225.
    - 225.
    - 225.
    - 225.
    - 225.
    - 225.
    - 225.
    - 225.
    - 225.
  farm_controller:
    control_discretisation: 1.
    controls:
      yaw:
        type: fixed

turbine:
  axial_induction: 0.33
  diameter: 178.3 # m
  thickness: 30. # 17.8 # m
  hub_height: 119.0 # m
  kernel: gaussian # king, gaussian
  force_scale_axial: 1
  force_scale_transverse: 3.
  power_scale: 1
  yaw_rate_limit: 0.3
  coefficients: induction