mode: simulation

simulation:
  name: 2d.1wt.yaw.s3
  is_dynamic: True
  total_time: 1000. # s
  time_step: 0.5 # s
  # set dimensions to three
  dimensions: 2 # -
  save_logs: True
  write_time_step: 1.0

flow:
  type: "steady"
  inflow_velocity: [9.0, 270.]  # [|U|, theta]
  kinematic_viscosity: 0.000015 # kg.m^-1.s^-1
  tuning_viscosity: 1. # kg.m^-1.s^-1
  mixing_length: 3. #30. #20 # m
  wake_mixing_length: 1.5 # D
  wake_mixing_width: 0.6  # D
  wake_mixing_offset: 3.0 # D
  wake_mixing_ml_max: 0 #25 # m
  density: 1.2 # kg.m^-3
  # set c.c. to 'none'
  continuity_correction: wfsim_gen #wfsim_gen # none, wfsim, (general)
  finite_element: MINI # TH, MINI

wind_farm:
  # adjust size and cells to dim=3
  size: [2000,1000,500]
  cells: [80, 40, 20]
  do_refine_turbines: 0 # n refinements
  refine_radius: 200. # m
  positions: # [x, y] m
    - [500, 500]
  yaw_angles: # [gamma] deg
    - 290.
  farm_controller:
    control_discretisation: 1.
    controls:
      yaw:
        type: series
        values:
          - [0., 270.]
          - [199.9, 270.]
          - [200.0, 300.]
          - [499.9, 300.]
          - [500.0, 285.]
          - [699.9, 285.]
          - [700.0, 270.]
          - [899.90, 270.]

turbine:
  axial_induction: 0.33
  diameter: 178.3 # m
  thickness: 30. # 17.8 # m
  hub_height: 119.0 # m
  kernel: king # king, gaussian
  force_scale_axial: 1
  force_scale_transverse: 3
  power_scale: 1
  yaw_rate_limit: 0.3
  coefficients: induction