mode: simulation

simulation:
  name: nine.02.rotating
  is_dynamic: True
  total_time: 900. # s
  time_step: 1. # s
  dimensions: 2 # -
  save_logs: True
  write_time_step: 10.0

flow:
  inflow_velocity: [9., 255]
  type: "steady"
#  inflow_velocity_series: # [t, |U|, theta]
#    - [0,   9., 255]
#    - [299,   9., 255]
#    - [600., 9., 195]
#    - [900., 9., 195]
  kinematic_viscosity: 0.000015 # kg.m^-1.s^-1
  tuning_viscosity: 0. # kg.m^-1.s^-1
  mixing_length: 10. #30. #20 # m
  wake_mixing_length: 1.5 # D
  wake_mixing_width: 0.6  # D
  wake_mixing_offset: 3.0 # D
  wake_mixing_ml_max: 25. # m
  density: 1.2 # kg.m^-3
  continuity_correction: wfsim # none, wfsim, (general)

wind_farm:
  size: [3000,3000]
  cells: [30, 30]
  do_refine_turbines: 1
  refine_radius: 100.
  positions: # [x, y] m
    - [600,500]
    - [1500, 500]
    - [2400, 500]
    - [600, 1500]
    - [1500, 1500]
    - [2400, 1500]
    - [600, 2400]
    - [1500, 2400]
    - [2400, 2400]
#    - [1300,500]
  yaw_angles: # [gamma] deg
    - 225.
    - 225.
    - 225.
    - 225.
    - 225.
    - 225.
    - 225.
    - 225.
    - 225.
#    - 270.
  farm_controller:
    control_discretisation: 1.
    yaw_control_type: fixed
#    yaw_series:
#      - [0, 270.]
#      - [10, 270.]
    axial_induction_control_type: fixed
#    axial_induction_series:
#      - [0., 0.33]
#      - [1., 0.33]
    # if turbine:coefficients:lut, then need pitch and torque control
    pitch_control_type: fixed
#    pitch_control_type: series
#    pitch_series:
#      - [0., 0.]
#      - [120.,20.]
    torque_control_type: fixed
#    torque_control_type: series
#    torque_series:
#      - [0., 1000.]
#      - [120., 1000.]

turbine:
  axial_induction: 0.33
  diameter: 178.4 # m
  thickness: 17.8 # m
  hub_height: 119.6 # m
  kernel: gaussian # king, gaussian
  deflection_scale: 3. #
  # type of coefficient calculation method [induction; lut]
  coefficients: induction
#  coefficients: lut
  pitch: 1.
  torque: 8. # currently linked to TSR directly