mode: supercontroller

ssc:
  port: 1638
  control_discretisation: 1.
  yaw_angles:
    - 270.
#  type: series
#  yaw_series:
#    - [0., 290.]
#    - [300., 250]
#    - [600., 290]
#  axial_induction_series:
#    - [0., 0.1]
#    - [300., 0.4]
#    - [600., 0.1]
  type: gradient_step
  prediction_horizon: 10.
  control_horizon: 1.
  transient_time: -1.
#  objective: tracking
  objective: maximisation
  power_reference:  #MW
    - [  0., 6.1]
    - [999., 7.1]
  control_signal: absolute
#  control_signal: relative

simulation:
  name: one.ssc.ctrl
  is_dynamic: True
  total_time: -1 # s
  time_step: 1. # s
  dimensions: 2 # -
  save_logs: False
  write_time_step: 10.0

flow:
#  type: "steady"
#  inflow_velocity: [9., 270.]  # [|U|, theta]
  type: series
  inflow_velocity_series: # [t, |U|, theta]
    - [0,   9., 270]
    - [60., 9., 290]
    - [180., 9., 250]
    - [300., 9., 290]
    - [400., 9., 250]
  kinematic_viscosity: 0.000015 # kg.m^-1.s^-1
  tuning_viscosity: 0. # kg.m^-1.s^-1
  mixing_length: 10. #30. #20 # m
  wake_mixing_length: 1.5 # D
  wake_mixing_width: 0.6  # D
  wake_mixing_offset: 3.0 # D
  wake_mixing_ml_max: 25. # m
  density: 1.2 # kg.m^-3
  continuity_correction: wfsim # none, wfsim, (general)

wind_farm:
  size: [1000,1000]
  cells: [10, 10]
  do_refine_turbines: 1
  refine_radius: 100.
  positions: # [x, y] m
    - [400,500]
  yaw_angles: # [gamma] deg
    - 270.

  farm_controller:
#    type: fixed
    control_discretisation: 1.
    yaw_control_type: series
    yaw_series:
      - [0, 270.]
      - [10, 270.]
    axial_induction_control_type: series
    axial_induction_series:
      - [0., 0.33]
      - [1., 0.33]

turbine:
  axial_induction: 0.33
  diameter: 178.4 # m
  thickness: 25. # m
  hub_height: 119.6 # m
  kernel: gaussian # king, gaussian
  deflection_scale: 3. #
  yaw_rate_limit: 0.3