#  turbine optimization config
# DTU10MWRef

mode: simulation

simulation:
  name: power_yaw
  is_dynamic: True
  total_time: 150. # s
  time_step: 0.5 # s
  dimensions: 2 # -
  save_logs: True
  write_time_step: 30.0

flow:
  type: "steady"
  inflow_velocity: [9., 270.]  # [|U|, theta]
  kinematic_viscosity: 0.000015 # kg.m^-1.s^-1
  tuning_viscosity: 0. # kg.m^-1.s^-1
  mixing_length: 10. #30. #20 # m
  density: 1.2 # kg.m^-3

wind_farm:
  size: [2000,1000]
  cells: [20, 10]
  do_refine_turbines: 1
  refine_radius: 150.
  positions: # [x, y] m
    - [400,500]
#    - [1300,500]
  yaw_angles: # [gamma] deg
    - 280.
#    - 270.

  farm_controller:
    control_discretisation: 1.
#    type: fixed
#    type: external
#    port: 1649
#    control_discretisation: 2.
    type: series
    yaw_series: # [time, yaw_0, ... , yaw_n]
      - [  0., 270.]
      - [299.9,270.]
      - [300., 290.]
#      - [499.9,290., 270.]
#      - [500., 270., 270.]
      - [700., 290.]
#    control_discretisation: 10.

turbine:
  axial_induction: 0.33
  diameter: 178.4 # m
  thickness: 17.8 # m
  hub_height: 119.6 # m
