mode: simulation

simulation:
  name: ssc_sim
  is_dynamic: True
  total_time: 59. # s
  time_step: 0.5 # s
  dimensions: 2 # -
  save_logs: True
  write_time_step: 10.0

flow:
  type: "steady"
  inflow_velocity: [8., 270.]  # [|U|, theta]
  kinematic_viscosity: 0.000015 # kg.m^-1.s^-1
  tuning_viscosity: 1. # kg.m^-1.s^-1
  mixing_length: 20. #30. #20 # m
  density: 1.2 # kg.m^-3

wind_farm:
  size: [2000,1000]
  cells: [20, 10]
  do_refine_turbines: 2
  refine_radius: 100.
  positions: # [x, y] m
    - [400,500]
    - [1300,500]
  yaw_angles: # [gamma] deg
    - 270.
    - 270.
  farm_controller:
    type: external
    port: 1649
    control_discretisation: 5.

turbine:
  axial_induction: 0.33
  diameter: 178.4 # m
  thickness: 17.8 # m
  hub_height: 119.6 # m
