#  turbine optimization config
# DTU10MWRef

mode: simulation

simulation:
  name: two_turbine_test
  is_dynamic: True
  total_time: 300. # s
  time_step: 1. # s
  dimensions: 2 # -
  save_logs: True
  write_time_step: 10.0

flow:
  type: "steady"
  inflow_velocity: [8., 270.]  # [|U|, theta]
  kinematic_viscosity: 0.000015 # kg.m^-1.s^-1
  tuning_viscosity: 1. # kg.m^-1.s^-1
  mixing_length: 30. #30. #20 # m
  density: 1.2 # kg.m^-3

wind_farm:
  size: [1000,2000]
  cells: [10, 20]
  do_refine_turbines: 1
  refine_radius: 150.
  positions: # [x, y] m
    - [400,500]
    - [400,1500]
  yaw_angles: # [gamma] deg
    - 260.
    - 270.

  farm_controller:
    control_discretisation: 20.
#    type: fixed
#    type: external
#    port: 1649
#    control_discretisation: 2.
    type: series
    yaw_series: # [time, yaw_0, ... , yaw_n]
      - [  0., 290, 250.]
      - [ 60., 290, 250.]
      - [300., 250, 290.]
#      - [0., 0.3, 0.,]
#      - [59., -0.3, 0.,]
#    control_discretisation: 10.

turbine:
  axial_induction: 0.33
  diameter: 178.4 # m
  thickness: 17.8 # m
  hub_height: 119.6 # m
