mode: supercontroller

ssc:
  port: 1652
  external_controls:
    - torque
    - yaw
    - pitch
  external_measurements:
    - generatorPower
    - rotorSpeed
    - azimuth
    - rotorThrust
    - rotorTorque
    - generatorTorque
    - nacelleYaw
    - bladePitch
  control_discretisation: 1.
#  type: fixed
  controls:
    yaw:
      type: series
      values:
        - [0., 270., 270.]
        - [1000., 270., 270.]
      rate_limit: 0.3
    pitch:
      type: series
      values:
        - [0., 0., 0.]
        - [299.9, 0., 0.]
        - [300., 3., 0.]
        - [1000., 3., 0.]
      rate_limit: 1.
      range: [-1., 25.]
    torque:
      type: series
      values:
        - [0., 8., 8.]
        - [1000., 8., 8.]
      rate_limit: 1.
      range: [3., 14.]
  transient_time: 120.
  prediction_horizon: 20.
  control_horizon: 1.
#  objective: tracking # [tracking; maximisation]
  plant: sowfa # [cm; sowfa] if sowfa: convert tsr to torque with tsr tracker
  sowfa_time_step: 0.2

simulation:
  name: two.ssc.ctrl
  is_dynamic: True
  total_time: -1 # s
  time_step: 1. # s
  dimensions: 2 # -
  save_logs: False
  write_time_step: 10.0

flow:
  type: "steady"
  inflow_velocity: [9., 270.]  # [|U|, theta]
  kinematic_viscosity: 0.000015 # kg.m^-1.s^-1
  tuning_viscosity: 0. # kg.m^-1.s^-1
  mixing_length: 10. #30. #20 # m
  wake_mixing_length: 1.5 # D
  wake_mixing_width: 0.6  # D
  wake_mixing_offset: 3.0 # D
  wake_mixing_ml_max: 25. # m
  density: 1.2 # kg.m^-3
  continuity_correction: wfsim # none, wfsim, (general)
  finite_element: MINI

wind_farm:
  size: [2000,1000]
  cells: [20, 10]
  do_refine_turbines: 1
  refine_radius: 100.
  positions: # [x, y] m
    - [400,500]
    - [1300,500]
  yaw_angles: # [gamma] deg
    - 290.
    - 270.

  farm_controller:
#    type: fixed
    control_discretisation: 1.
    controls:
      yaw:
        type: series
        values:
          - [0, 280., 270.]
          - [10, 280., 270.]
      pitch:
        type: series
        values:
          - [0., 0., 0.]
          - [10., 0.,0.]
      torque:
        type: series
        values:
          - [0., 8., 8.]
          - [10., 8., 8.]

turbine:
  axial_induction: 0.33
  diameter: 178.4 # m
  thickness: 17.8 # m
  hub_height: 119.6 # m
  kernel: gaussian # king, gaussian
  deflection_scale: 3. #
  yaw_rate_limit: 0.3
  coefficients: lut
  pitch: 0.
  torque: 8.