mode: supercontroller

ssc:
  port: 1652
  control_discretisation: 1.
  mode: pitch_torque # [induction; pitch_torque]
#  type: fixed
  yaw_angles:
    - 290.
    - 270.
#  type: series
#  yaw_series:
#      - [0., 290, 270.]
#      - [59., 250, 270.]
  type: gradient_step # [fixed; series; gradient_step]
  prediction_horizon: 20.
  control_horizon: 1.
  transient_time: 120.
  objective: tracking # [tracking; maximisation]
  power_reference:  #MW
    - [  0., 6.1]
    - [999., 7.1]
  plant: sowfa # [cm; sowfa] if sowfa: convert tsr to torque with tsr tracker
  sowfa_time_step: 0.2

simulation:
  name: two.ssc.ctrl
  is_dynamic: True
  total_time: -1 # s
  time_step: 1. # s
  dimensions: 2 # -
  save_logs: False
  write_time_step: 10.0

flow:
  type: "steady"
  inflow_velocity: [9., 270.]  # [|U|, theta]
  kinematic_viscosity: 0.000015 # kg.m^-1.s^-1
  tuning_viscosity: 0. # kg.m^-1.s^-1
  mixing_length: 10. #30. #20 # m
  wake_mixing_length: 1.5 # D
  wake_mixing_width: 0.6  # D
  wake_mixing_offset: 3.0 # D
  wake_mixing_ml_max: 25. # m
  density: 1.2 # kg.m^-3
  continuity_correction: wfsim # none, wfsim, (general)
  finite_element: MINI

wind_farm:
  size: [2000,1000]
  cells: [20, 10]
  do_refine_turbines: 1
  refine_radius: 100.
  positions: # [x, y] m
    - [400,500]
    - [1300,500]
  yaw_angles: # [gamma] deg
    - 290.
    - 270.

  farm_controller:
#    type: fixed
    control_discretisation: 1.
    yaw_control_type: series
    yaw_series:
      - [0, 290., 270.]
      - [0, 270., 270.]
    axial_inductioN_control_type: none
    pitch_control_type: series
    pitch_series:
      - [0., 0., 0.]
      - [10., 5., 5.]
    torque_control_type: series
    torque_series:
      - [0., 10., 10.]
      - [10., 8., 8.]
turbine:
  axial_induction: 0.33
  diameter: 178.4 # m
  thickness: 17.8 # m
  hub_height: 119.6 # m
  kernel: gaussian # king, gaussian
  deflection_scale: 3. #
  yaw_rate_limit: 0.3
  coefficients: lut
  pitch: 0.
  torque: 8.